/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto;

import conexion.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import static reto.v_Estudiante.id_estudiante;
import static reto.v_Estudiante.numero_cursos;


/**
 *
 * @author @Jogonpav
 */
public class v_Cursos_Matriculados extends javax.swing.JFrame {
    ArrayList<Integer> id_cursos;
    ArrayList<String> nombre_cursos;
    static int id_curso_seleccionado; //variable que permite mostrar el contenido del curso matriculado 
    String datos_tabla [] = new String[4];
    String datos_horario [] = new String[7];
    

    public v_Cursos_Matriculados() {
        initComponents();        
        DefaultListModel model = new DefaultListModel ();
        id_curso_seleccionado = -1; //inicializa el id seleccionado
        int pos = 0;        
        id_cursos = new ArrayList();  
        nombre_cursos = new ArrayList();
        try {
            conexion cn = new conexion();
            Connection conn = cn.conectar();
            Statement stmt = conn.createStatement();
            String query = "SELECT CURSOS_ID FROM estudiantesxcurso WHERE ESTUDIANTES_ID="+id_estudiante; //traer id de cursos que se encuentran matriculados para el estudiante
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next()){
                id_cursos.add(rs.getInt(1)); //guardamos los id de los cursos y luegos consultamos el nombre en la tabla cursos
            }
            for (int i = 0; i < id_cursos.size(); i++) {
                query = "SELECT nombre FROM cursos WHERE ID="+(id_cursos.get(i));  // traemos los nombres de los cursos              
                rs = stmt.executeQuery(query);
                 while(rs.next()){
                    nombre_cursos.add(rs.getString(1)); //guaramos los nombres
                    model.addElement(rs.getString(1));//
                    }
            }
            jList1.setModel(model);
        }
        catch(SQLException ex){
            System.out.println(ex);
        }
        jTextField1.setText(numero_cursos + " / 3");
        jList1.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CURSOS MATRICULADOS");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("CURSOS MATRICULADOS POR EL ESTUDIANTE");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Seleccione un curso para ver información");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sábado", "Domingo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Profesor", "Ubicación", "Fecha Inicio", "Fecha Cierre"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        jButton2.setText("Ver Contenido del curso");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));

        jLabel4.setText("CANTIDAD DE CURSOS");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextField1.setText("- / -");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jButton2)
                            .addComponent(jScrollPane3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        verInformacionCurso();
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(id_curso_seleccionado >=0){
            v_Mostrar_Contenidos_Cmatriculados v_most_contcursos = new v_Mostrar_Contenidos_Cmatriculados();
            v_most_contcursos.setLocationRelativeTo(null);
            v_most_contcursos.setResizable(false);
            v_most_contcursos.setVisible(true);
           
            
                //SELECT titulo, descripcion FROM contenidos WHERE curso_id = 4
        }else{
            jLabel3.setText("Seleccione un curso de la lista anterior");            
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_Cursos_Matriculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_Cursos_Matriculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_Cursos_Matriculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_Cursos_Matriculados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_Cursos_Matriculados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public void verInformacionCurso() {     
        jLabel3.setText(""); 
        id_curso_seleccionado= id_cursos.get(jList1.getSelectedIndex()); // se guarda el id del curso seleccionado
        try{ //estableciendo conexión
            conexion cn = new conexion();
            Connection conn = cn.conectar();
            Statement stmt = conn.createStatement();
            String query = "SELECT ubicacion, fecha_inicio, fecha_fin, profesores_id FROM cursos WHERE ID ="+id_curso_seleccionado; //consulta en la tabla cursos con el id del cursos
            ResultSet rs = stmt.executeQuery(query);
            while (rs.next()){ 
                datos_tabla[1] = rs.getString(1);
                datos_tabla[2] = rs.getString(2);
                datos_tabla[3] = rs.getString(3);
                if (rs.getString(4) == null){
                    datos_tabla[0] = "No Asignado";
                }else{                        
                    query = "SELECT nombre FROM profesores WHERE ID ="+(rs.getString(4));
                    rs = stmt.executeQuery(query);
                    while(rs.next()){
                        datos_tabla[0] = rs.getString(1);
                    }                   
                }  
            }        
            DefaultTableModel tabla_curso = new DefaultTableModel (); //estableciendo modelo tabla
            tabla_curso.addColumn("Profesor"); //agregando columnas al motelo tabla
            tabla_curso.addColumn("Ubicación");
            tabla_curso.addColumn("Fecha Inicio");
            tabla_curso.addColumn("Fecha Cierre");
            jTable2.setModel(tabla_curso);//agregando el modelo tabla al jTable
            tabla_curso.addRow(datos_tabla);
            query = "SELECT horario_id FROM cursos WHERE ID ="+ (id_cursos.get(jList1.getSelectedIndex())); //consulta para traer la llave foranea horario_id que enlasa a la tabla horario
            rs = stmt.executeQuery(query); //haciedo la consulta
            while(rs.next()){
                query = "SELECT lunes, martes, miercoles, jueves, viernes, sabado, domingo FROM horario WHERE id ="+ (rs.getInt(1));  //guardar la consulta del horario_id
            }
            rs = stmt.executeQuery(query);
            while(rs.next()){
                datos_horario [0] = rs.getString(1); //agragamos las franjas del horario en el array
                datos_horario [1] = rs.getString(2);
                datos_horario [2] = rs.getString(3);
                datos_horario [3] = rs.getString(4);
                datos_horario [4] = rs.getString(5);
                datos_horario [5] = rs.getString(6);
                datos_horario [6] = rs.getString(7);
            }
            DefaultTableModel tabla_horario = new DefaultTableModel();
            tabla_horario.addColumn("Lunes"); 
            tabla_horario.addColumn("Martes");
            tabla_horario.addColumn("Miércoles");
            tabla_horario.addColumn("Jueves");
            tabla_horario.addColumn("Viernes");
            tabla_horario.addColumn("Sábado");
            tabla_horario.addColumn("Domingo");
            jTable1.setModel(tabla_horario);
            tabla_horario.addRow(datos_horario); //agregamos la fila con las franjas del horario gruardadas anteiormente
        }
        catch(SQLException ex){
            System.out.println(ex);
        }

    }
    
}
