/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reto;

import POFO.pofo_cursos;
import conexion.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author @Jogonpav
 */
public class v_Registrar_Curso extends javax.swing.JFrame {
    pofo_cursos cur = new pofo_cursos();
    /**
     * Creates new form v_Registrar_Curso
     */
    public v_Registrar_Curso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox15 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Registrar Curso");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setText("Ingrese la siguiente información para registrar un curso");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Nombre del Curso");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Horario");

        jCheckBox1.setText("Lunes");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Martes");

        jCheckBox3.setText("Miercoles");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Jueves");

        jCheckBox5.setText("Viernes");

        jCheckBox6.setText("Sábado");

        jCheckBox7.setText("Domingo");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", " " }));
        jComboBox1.setSelectedIndex(-1);

        jLabel5.setText("Día");

        jLabel6.setText("Hora Inicio");

        jLabel7.setText("Hora Cierre");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        jComboBox2.setSelectedIndex(-1);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", " " }));
        jComboBox3.setSelectedIndex(-1);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        jComboBox4.setSelectedIndex(-1);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", " " }));
        jComboBox5.setSelectedIndex(-1);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        jComboBox6.setSelectedIndex(-1);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", " " }));
        jComboBox7.setSelectedIndex(-1);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        jComboBox8.setSelectedIndex(-1);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", " " }));
        jComboBox9.setSelectedIndex(-1);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        jComboBox10.setSelectedIndex(-1);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", " " }));
        jComboBox11.setSelectedIndex(-1);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        jComboBox12.setSelectedIndex(-1);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", " " }));
        jComboBox13.setSelectedIndex(-1);

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6:00", "7:00", "8:00", "9:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00" }));
        jComboBox14.setSelectedIndex(-1);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Salón");

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "101", "102", "103", "201", "202", "203", "301", "302", "303", "401", "402", "403" }));
        jComboBox15.setSelectedIndex(-1);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("Fecha de inicio");

        jDateChooser1.setMaxSelectableDate(new java.util.Date(253372600862000L));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("Fecha de cierre");

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(0, 0, 255));

        jLabel12.setForeground(new java.awt.Color(0, 0, 255));

        jLabel13.setForeground(new java.awt.Color(0, 0, 255));

        jLabel14.setForeground(new java.awt.Color(0, 0, 255));

        jLabel15.setForeground(new java.awt.Color(0, 0, 255));

        jLabel16.setForeground(new java.awt.Color(0, 0, 255));

        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("Finalizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel5))
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox3)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(1, 1, 1)))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel9)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox3)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox4)
                            .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox5)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox6)
                            .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox7)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        jLabel12.setText("");
        jLabel15.setText("");
        jLabel16.setText("");
        jLabel11.setText("");
        jLabel13.setText("");
        jLabel14.setText(""); 
        //Cargar datos al objeto curso
        cur.setNombre_cursos(jTextField1.getText()); 
        cur.setSalon(String.valueOf(jComboBox15.getSelectedItem()));
        cur.setFecha_inicio(String.valueOf(((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText())); //Convertir fecha a String para poder guardar en la base de datos
        cur.setFecha_fin(String.valueOf(((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText()));
        int count_dias = 0;
        int pos_horario = 0;
        if(validarHorario()){//se procede a validar todos los campos del curso
            try{
                conexion cn = new conexion();
                Connection conn = cn.conectar();
                Statement stmt = conn.createStatement(); //GUARDAR LOS DATOS DE UN CURSO NUEVO (SIGUIENTE LINEA)
                String query = "INSERT INTO cursos (nombre,ubicacion,fecha_inicio,fecha_fin) VALUES ('"+cur.getNombre_cursos()+"','"+cur.getSalon()+"','"+cur.getFecha_inicio()+"','"+cur.getFecha_fin()+"')";
                stmt.executeUpdate(query);
                ResultSet rs;
                query = "SELECT COUNT(*) FROM horario"; //Obtner ultimo campo guardado en la tabla horario, ya que este va a permitir agregar en esta posición un día si el anterior dia fue registrado, si lunes fue registrado es necesario registrar los siguientes días en est posición
                rs = stmt.executeQuery(query);               
                while (rs.next())
                    pos_horario = rs.getInt(1); //fin coonsulta del utlimo campo
                if (jCheckBox1.isSelected()){//LUNES si está seleccionado se guarda mediante un insert ya que se agregará una nueva fila
                   count_dias ++;
                   cur.setDia((String)jComboBox1.getSelectedItem()+" - "+(String)jComboBox2.getSelectedItem());
                   query = "INSERT INTO horario (Lunes) VALUES ('"+cur.getDia()+"')";
                   stmt.executeUpdate(query);    

                }
                if (jCheckBox2.isSelected()){ //MARTES
                    cur.setDia((String)jComboBox5.getSelectedItem()+" - "+(String)jComboBox6.getSelectedItem());
                    if (count_dias >=1){//Martes si está seleccionado y lunes fue guardado, el valor de martes se actualiza en la fila de lunes
                        count_dias ++; 
                        query = "UPDATE horario SET Martes='"+cur.getDia()+"' Where ID="+(pos_horario+1); //pos_horario+1 siginifica que el usuario ya hizo un registro en horario en las lineas anteriores
                        stmt.executeUpdate(query);
                    }else{
                        count_dias ++;                    
                        query = "INSERT INTO horario (Martes) VALUES ('"+cur.getDia()+"')";
                        stmt.executeUpdate(query);   
                    }
                }
                if (jCheckBox3.isSelected()){//MIERCOLES
                    cur.setDia((String)jComboBox3.getSelectedItem()+" - "+(String)jComboBox8.getSelectedItem());
                    if (count_dias >=1){
                        count_dias ++;     
                        query = "UPDATE horario SET Miercoles='"+cur.getDia()+"' Where ID="+(pos_horario+1)+"";
                        stmt.executeUpdate(query);
                    }else{
                        count_dias ++;                    
                        query = "INSERT INTO horario (Miercoles) VALUES ('"+cur.getDia()+"')";
                        stmt.executeUpdate(query);   
                    }
                }
                if (jCheckBox4.isSelected()){ //JUEVES
                    cur.setDia((String)jComboBox7.getSelectedItem()+" - "+(String)jComboBox10.getSelectedItem());
                    if (count_dias >=1){
                        count_dias ++;       
                        query = "UPDATE horario SET Jueves='"+cur.getDia()+"' Where ID="+(pos_horario+1);
                        stmt.executeUpdate(query);
                    }else{
                        count_dias ++;                    
                        query = "INSERT INTO horario (Jueves) VALUES ('"+cur.getDia()+"')";
                        stmt.executeUpdate(query);   
                    }
                }
                if (jCheckBox5.isSelected()){ //VIERNES
                    cur.setDia((String)jComboBox9.getSelectedItem()+" - "+(String)jComboBox12.getSelectedItem());
                    if (count_dias >=1){
                        count_dias ++;       
                        query = "UPDATE horario SET Viernes='"+cur.getDia()+"' Where ID="+(pos_horario+1);
                        stmt.executeUpdate(query);
                    }else{
                        count_dias ++;                    
                        query = "INSERT INTO horario (Viernes) VALUES ('"+cur.getDia()+"')";
                        stmt.executeUpdate(query);   
                    }
                }            
                if (jCheckBox6.isSelected()){ //SABADO
                    cur.setDia((String)jComboBox13.getSelectedItem()+" - "+(String)jComboBox14.getSelectedItem());
                    if (count_dias >=1){
                        count_dias ++;       
                        query = "UPDATE horario SET Sabado='"+cur.getDia()+"' Where ID="+(pos_horario+1);
                        stmt.executeUpdate(query);
                    }else{
                        count_dias ++;                    
                        query = "INSERT INTO horario (Sabado) VALUES ('"+cur.getDia()+"')";
                        stmt.executeUpdate(query);   
                    }
                }
                if (jCheckBox7.isSelected()){ //SABADO
                    cur.setDia((String)jComboBox11.getSelectedItem()+" - "+(String)jComboBox4.getSelectedItem());
                    if (count_dias >=1){
                        count_dias ++;       
                        query = "UPDATE horario SET Domingo='"+cur.getDia()+"' Where ID="+(pos_horario+1);
                        stmt.executeUpdate(query);
                    }else{
                        count_dias ++;                    
                        query = "INSERT INTO horario (Domingo) VALUES ('"+cur.getDia()+"')";
                        stmt.executeUpdate(query);   
                    }//FINALIZA GUARDADO DEL CAMPO HORARIO
                }
                query = "SELECT COUNT(*) FROM cursos"; //Esta consulta obtiene la utlima posición del curso guardado, para poder relacionar la posición del curso registrado con la posición del horario
                rs = stmt.executeQuery(query);
                int pos_cursos =0;
                while(rs.next())
                    pos_cursos = rs.getInt(1);
                query = "UPDATE cursos SET Horario_id="+(pos_horario+1)+" Where ID="+(pos_cursos); //relacion de curso y horario
                stmt.executeUpdate(query);
            }catch(SQLException e){System.out.println(e);}
            JOptionPane.showMessageDialog(this, "Curso Registrado con Exito", "Guardado con éxito",JOptionPane.INFORMATION_MESSAGE);
            resetValores();
            
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_Registrar_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_Registrar_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_Registrar_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_Registrar_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_Registrar_Curso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private boolean validarHorario(){ 
        boolean respuesta = true; 
        if(jTextField1.getText().equals("")){//validacion si los campos estan rellenados, 
            respuesta =false; 
            jLabel12.setText("Inserte el Nombre del Curso");
        }//Validación que el usuario seleccione al menos una franja de hoario del checkbox del horario (Siguiente linea) 
        if (!(jCheckBox1.isSelected() || jCheckBox2.isSelected() || jCheckBox3.isSelected() || jCheckBox4.isSelected() || jCheckBox5.isSelected() || jCheckBox6.isSelected() || jCheckBox7.isSelected()) ){
            respuesta =false; 
            jLabel11.setText("Seleccione una franja de horario");
        }else {
            if (jCheckBox1.isSelected()){ //Si el día está seleccionado, es necesario que se valide, que el usuario seleccione una hora de inicio y fin, y que la hora de inicio no sea igual o mayor a la hora de cierre
                if (jComboBox1.getSelectedIndex()==-1 || jComboBox2.getSelectedIndex()==-1 || (jComboBox1.getSelectedIndex()==jComboBox2.getSelectedIndex()) || (jComboBox1.getSelectedIndex()>=jComboBox2.getSelectedIndex()) ){
                    respuesta =false; 
                    jLabel11.setText("Seleccione HORA Inicio y Fin");
                    jLabel16.setText("Verifique que inicio sea mayor a fin ");
                }
            }
            if (jCheckBox2.isSelected()){
                if (jComboBox5.getSelectedIndex()==-1 || jComboBox6.getSelectedIndex()==-1 || (jComboBox5.getSelectedIndex()==jComboBox6.getSelectedIndex()) || (jComboBox5.getSelectedIndex()>=jComboBox6.getSelectedIndex()) ){
                    respuesta =false; 
                    jLabel11.setText("Seleccione HORA Inicio y Fin");
                    jLabel16.setText("Verifique que inicio sea mayor a fin ");
                }
            } 
            if (jCheckBox3.isSelected()){
                if ((jComboBox3.getSelectedIndex()==-1 || jComboBox8.getSelectedIndex()==-1) || (jComboBox3.getSelectedIndex()==jComboBox8.getSelectedIndex()) || (jComboBox3.getSelectedIndex()>=jComboBox8.getSelectedIndex()) ){
                    respuesta =false; 
                    jLabel11.setText("Seleccione HORA Inicio y Fin");
                    jLabel16.setText("Verifique que inicio sea mayor a fin ");
                }
            }
            if (jCheckBox4.isSelected()){
                if (jComboBox7.getSelectedIndex()==-1 || jComboBox10.getSelectedIndex()==-1 || (jComboBox7.getSelectedIndex()==jComboBox10.getSelectedIndex()) || (jComboBox7.getSelectedIndex()>=jComboBox10.getSelectedIndex()) ){
                    respuesta =false; 
                    jLabel11.setText("Seleccione HORA Inicio y Fin");
                    jLabel16.setText("Verifique que inicio sea mayor a fin ");
                }
            }  
            if (jCheckBox5.isSelected()){
                if (jComboBox9.getSelectedIndex()==-1 || jComboBox12.getSelectedIndex()==-1 || (jComboBox9.getSelectedIndex()==jComboBox12.getSelectedIndex()) || (jComboBox9.getSelectedIndex()>=jComboBox12.getSelectedIndex()) ){
                    respuesta =false; 
                    jLabel11.setText("Seleccione HORA Inicio y Fin");
                    jLabel16.setText("Verifique que inicio sea mayor a fin ");
                }
            }
            if (jCheckBox6.isSelected()){
                if (jComboBox13.getSelectedIndex()==-1 || jComboBox14.getSelectedIndex()==-1 || (jComboBox13.getSelectedIndex()==jComboBox14.getSelectedIndex()) || (jComboBox13.getSelectedIndex()>=jComboBox14.getSelectedIndex()) ){
                    respuesta =false; 
                    jLabel11.setText("Seleccione HORA Inicio y Fin");
                    jLabel16.setText("Verifique que inicio sea mayor a fin ");
                }
            }   
            if (jCheckBox7.isSelected()){
                if (jComboBox11.getSelectedIndex()==-1 || jComboBox4.getSelectedIndex()==-1 || (jComboBox11.getSelectedIndex()==jComboBox4.getSelectedIndex()) || (jComboBox11.getSelectedIndex()>=jComboBox4.getSelectedIndex()) ){
                    respuesta =false; 
                    jLabel11.setText("Seleccione HORA Inicio y Fin");
                    jLabel16.setText("Verifique que inicio sea mayor a fin ");
                }
            } //FINALIZA VALIDACIÓN DE HROA DE INICIO Y FIN
        }
            
        if(jComboBox15.getSelectedIndex()==-1){
            respuesta =false; 
            jLabel15.setText("Seleccione un curso");
        }
        if(jDateChooser1.getDate()==null){
            respuesta =false; 
            jLabel13.setText("Seleccione una fecha");
        }
        if(jDateChooser2.getDate()==null){
            respuesta =false; 
            jLabel14.setText("Seleccione una fecha");
        }
        
        return respuesta;
    }
    public void resetValores() {    //FUNCIÓN PERMITE INICIALIZAR A TODOS LOS CAMPOS POR DEFECTOVS
            jTextField1.setText("");
            jComboBox15.setSelectedIndex(-1);
            jCheckBox1.setSelected(false);
            jCheckBox2.setSelected(false);
            jCheckBox3.setSelected(false);
            jCheckBox4.setSelected(false);
            jCheckBox5.setSelected(false);
            jCheckBox6.setSelected(false);
            jCheckBox7.setSelected(false);
            jComboBox1.setSelectedIndex(-1);
            jComboBox2.setSelectedIndex(-1);
            jComboBox5.setSelectedIndex(-1);
            jComboBox6.setSelectedIndex(-1);
            jComboBox3.setSelectedIndex(-1);
            jComboBox8.setSelectedIndex(-1);
            jComboBox7.setSelectedIndex(-1);
            jComboBox10.setSelectedIndex(-1);
            jComboBox9.setSelectedIndex(-1);
            jComboBox12.setSelectedIndex(-1);
            jComboBox13.setSelectedIndex(-1);
            jComboBox14.setSelectedIndex(-1);
            jComboBox11.setSelectedIndex(-1);
            jComboBox4.setSelectedIndex(-1);
            jDateChooser1.setCalendar(null); 
            jDateChooser2.setCalendar(null); 
    }
}
